# version: '3'
# services:
#   web:
#     build: .
#     ports:
#      - "5000:5000"

version: '3.8'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python main.py 
    env_file:
      - .env
    ports: 
      - 8080:8080
    networks:
      - app_network

  ui:
    build:
      context: ./
      dockerfile: Dockerfile
    command: streamlit run app.py  
    env_file:
      - .env
    ports: 
      - 8501:8501
    networks:
      - app_network
    depends_on:
      - api   

networks:
  app_network:
    driver: bridge